return {
  { start=0.0, stop=5.5, "Although the melody from the graveyard gave Martin a shiver, it felt oddly pleasant." },
  { start=6.0, stop=8.5, "Like greeting a long missed friend." },
  { start=9.0, stop=10.8, "Is this the end?" },
  { start=11.0, stop=16.5, "Did he gain back his memories only to learn that the graveyard would be his final destination?" },
  { start=17.0, stop=20.5, "Was the crash so hard that he didn't survive?" },
  { start=20.8, stop=24.5, "And this friend, was it ... death?" },
  { start=29.0, stop=32.5, "But then Martin heard the last melody he needed:" },
  { start=32.8, stop=35.5, "the bells of the little church next to the graveyard." },
  { start=35.8, stop=38.5, "This! This was his home." },
  { start=39.0, stop=45.5, "This was where he lived with his brothers and sisters and all the other swallows." },
  { start=46.0, stop=49.5, "And Martin also remembered why he was doing this journey at all." },
  { start=49.7, stop=52.2, "He was a migrant bird!" },
  { start=53.6, stop=60.0, "And if he would hurry, he might catch up to his folks before the winter comes." },
  { start=61.0, stop=64.0, "Looking out for trees, of course. " },
}